In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('/content/fever_dataset.csv')

In [5]:
df

     Person COVID  FLU Fever
0        P1    No   No    No
1        P2    No   No    No
2        P3    No   No    No
3        P4    No  Yes   Yes
4        P5   Yes   No   Yes
...     ...   ...  ...   ...
1795  P1796   Yes   No   Yes
1796  P1797    No  Yes   Yes
1797  P1798   Yes   No   Yes
1798  P1799   Yes   No   Yes
1799  P1800   Yes   No    No

[1800 rows x 4 columns]

In [6]:
df.drop(columns=['Person'],inplace=True)

In [7]:
df.head()

  COVID  FLU Fever
0    No   No    No
1    No   No    No
2    No   No    No
3    No  Yes   Yes
4   Yes   No   Yes

In [8]:
df.tail()

     COVID  FLU Fever
1795   Yes   No   Yes
1796    No  Yes   Yes
1797   Yes   No   Yes
1798   Yes   No   Yes
1799   Yes   No    No

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1800 entries, 0 to 1799
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   COVID   1800 non-null   object
 1   FLU     1800 non-null   object
 2   Fever   1800 non-null   object
dtypes: object(3)
memory usage: 42.3+ KB

In [10]:
df.isnull().sum()

COVID    0
FLU      0
Fever    0
dtype: int64

In [11]:
df.describe()

       COVID   FLU Fever
count   1800  1800  1800
unique     2     2     2
top       No    No    No
freq    1244  1257   920

In [14]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import CategoricalNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [15]:
X = df[['COVID', 'FLU']]
y = df['Fever']

In [16]:
X_encoder = OrdinalEncoder()
X_encoded = X_encoder.fit_transform(X)

In [17]:
y_encoder = OrdinalEncoder()
y_encoded = y_encoder.fit_transform(y.values.reshape(-1, 1)).ravel()

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X_encoded, y_encoded, test_size=0.2, random_state=42)

In [19]:
model = CategoricalNB()

In [20]:
model.fit(X_train, y_train)

CategoricalNB()

In [21]:
y_pred = model.predict(X_test)

In [22]:
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.85

In [23]:
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Classification Report:
               precision    recall  f1-score   support

         0.0       0.91      0.80      0.85       191
         1.0       0.80      0.91      0.85       169

    accuracy                           0.85       360
   macro avg       0.85      0.85      0.85       360
weighted avg       0.86      0.85      0.85       360

In [24]:
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Confusion Matrix:
 [[153  38]
 [ 16 153]]